[package]
name = "iced_ext"
version = "0.1.0"
edition = "2024"

[dependencies]
iced_core = { git = "https://github.com/iced-rs/iced", branch = "master" }
iced_widget = { git = "https://github.com/iced-rs/iced", branch = "master" }
